### ISSUE TITLE
Build error, cannot open crtend_android.o

### ISSUE THREAD

**Issue by lafferjm** [frmdstryr/p4a-numpy#1]
I am trying to use this to correct the -lcrystax not found error, and it goes away with it.  But now I am seeing the below error.

.p4a config
--private ./
--package=org.test.numpytest
--name "numpy test"
--version 0.1
--bootstrap=sdl2
--requirements python3crystax==3.6,kivy,numpy
--arch armeabi-v7a
--sdk_dir /Users/me/Library/Android/sdk/
--ndk_dir /Users/me/.buildozer/crystax-ndk/
--android_api 21
--ndk_version 10.3.2

crystax-ndk/toolchains/arm-linux-androideabi-5/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/5.3/../../../../arm-linux-androideabi/bin/ld: error: cannot open crtend_android.o: No such file or directory
collect2: error: ld returned 1 exit status

I have checked and that file exists in crystax-ndk/platforms/android-21/arch-arm/usr/lib.  

What can I do to correct this error?

**Comment by frmdstryr** [comment]
Add a `-L/full/path/to/crystax-ndk/platforms/android-21/arch-arm/usr/lib` flag to tell the loader where to find it.

Also your setting android api to 21 but referencing android-19 so pick one or the other.

**Comment by lafferjm** [comment]
Sorry, made a mistake in my description.  I checked in platforms/android-21.  I have added that path to the numpy recipe, and it is failing with the same error.

**Comment by frmdstryr** [comment]
Can you show your exact changes? Also maybe a more complete log to see what flags it's sending?

**Comment by frmdstryr** [comment]
Try adding env['SYSROOT'] = '/Users/lafferjm/.buildozer/crystax-ndk/platforms/android-21/arch-arm'

It seems the flags are being pulled out somewhere along the line so the only other thing I can think of is to read the numpy setup.py source to see what it's doing.

I never tried this recipe on OSX.

**Comment by lafferjm** [comment]
Which OS did you run it on?  Also adding sysroot didn't work either, I will take a look at the setup.py source.

**Comment by frmdstryr** [comment]
Linux (ubuntu 16.04), also I've never tested it with python3crystax and I use a modified version p4a from https://github.com/codelv/enaml-native-cli/tree/master/python-for-android. You may be able to diff to see what else may have changed, but I looked and didn't see anything obvious.
